// <auto-generated />
using LoanComparer.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanComparer.Application.Migrations
{
    [DbContext(typeof(LoanComparerContext))]
    partial class LoanComparerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoanComparer.Application.Model.JobType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Name");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            Name = "JobType1"
                        },
                        new
                        {
                            Name = "JobType2"
                        },
                        new
                        {
                            Name = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
